[package]
name = "hifumi"
version.workspace = true
edition.workspace = true

publish = true
description = "A serialization library for migrating data between different versions"
license = "Apache-2.0"
repository = "https://github.com/celestia-island/hifumi"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
_macros = { path = "../macros", version = "0.1.0", package = "hifumi-macros" }

anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }

serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
